using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class IsPlayerOnTop:MonoBehaviour
{

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

void OnTriggerEnter2D(Collider2D other) {
    if (other.CompareTag("Player")) {
       gameObject.tag = "PlayerIsOnIt";
    }
}

void OnTriggerExit2D(Collider2D other) {
    if (other.CompareTag("Player")) {
         gameObject.tag = "PressurePlatable";
    }
}
}
