using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class MainMenu : MonoBehaviour
{
    public string newGameScene;
    public string continueGameScene;
    
    public void startGame()
    {
        Debug.Log("Main Menu: New Game");
        SceneManager.LoadScene(newGameScene);
    }

    public void continueGame()
    {
        Debug.Log("Main Menu: Continue Game");
        SceneManager.LoadScene(continueGameScene);
    }

    public void endGame()
    {
        Debug.Log("Main Menu: Quit Game");
        Application.Quit();
    }
}
