using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ButtonBoth:MonoBehaviour
{

public GameObject door;
public SpriteRenderer spriteRenderer;
public Sprite originalSprite;
public Sprite activatedSprite;
public bool startActivated = false;
private Collider2D Stein = null;
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
       if (startActivated == true ) {
       spriteRenderer.sprite = activatedSprite;
    } else {
spriteRenderer.sprite = originalSprite;}  

       if(Stein!=null && Stein.CompareTag("PlayerIsOnIt")){
		startActivated = true;
		spriteRenderer.sprite = activatedSprite;
openDoor();	
	}
    }

void OnTriggerEnter2D(Collider2D other) {
    Stein = other;
    if (other.CompareTag("PlayerIsOnIt")) {
       startActivated = true;
       spriteRenderer.sprite = activatedSprite;
	  openDoor();	
    }
  
	
}

void openDoor(){
door.SetActive(false);
}
}



