using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ButtonDTwo:MonoBehaviour
{

public SpriteRenderer spriteRenderer;
public Sprite originalSprite;
public Sprite activatedSprite;
public bool startActivated = false;
private Collider2D Stein = null;
public bool zweiAn = false;
private AudioSource audioSource; // Reference to the AudioSource component
public AudioClip pressedSound; // The sound clip to be played
    // Start is called before the first frame update
    void Start()
    {
        audioSource = GetComponent<AudioSource>(); 
    }

    // Update is called once per frame
    void Update()
    {
       if (startActivated == true ) {
       spriteRenderer.sprite = activatedSprite;
    } else {
spriteRenderer.sprite = originalSprite;}  

       if(Stein!=null && Stein.CompareTag("PlayerIsOnIt")){
		startActivated = true;
		spriteRenderer.sprite = activatedSprite;
		zweiAn = true;	
	}
    }

void OnTriggerEnter2D(Collider2D other) {
    Stein = other;
    if (other.CompareTag("PressurePlatable")||other.CompareTag("Player")) {
       startActivated = true;
       spriteRenderer.sprite = activatedSprite;
    if(!zweiAn){
        audioSource.PlayOneShot(pressedSound);
       }
	zweiAn = true;
	  
    }
  
	
}


}



