using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DynamicWall : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    void OnTriggerEnter2D(Collider2D col)
    {
        if(col.CompareTag("Player")){gameObject.GetComponent<EdgeCollider2D>().enabled = false;}
    }

    void OnTriggerExit2D(Collider2D col)
    {
        if(col.CompareTag("Player")){gameObject.GetComponent<EdgeCollider2D>().enabled = true;}
    }
}
