using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerPressurePlateMod: MonoBehaviour
{

public SpriteRenderer spriteRenderer;
public Sprite originalSprite;
public Sprite activatedSprite;
public GameObject door;
public AudioSource audioSource; // Reference to the AudioSource component
public AudioClip buttonClickSound; // The sound clip to be played
public AudioClip doorOpenSound;
private bool isActive = false;
    // Start is called before the first frame update
    void Start()
    {
          audioSource = GetComponent<AudioSource>();
    }

    // Update is called once per frame
    void Update()
    {
        
    }

void OnTriggerEnter2D(Collider2D other) {
    //if (other.CompareTag("Player")) {
    //   spriteRenderer.sprite = activatedSprite;
    //}
    spriteRenderer.sprite = activatedSprite;
    if(!isActive){
    audioSource.PlayOneShot(buttonClickSound);
    audioSource.PlayOneShot(doorOpenSound);
    isActive = true;
    }
    

    door.SetActive(false);
}

/*
void OnTriggerExit2D(Collider2D other) {
    if (other.CompareTag("Player")) {
         spriteRenderer.sprite = originalSprite;
    }
    spriteRenderer.sprite = originalSprite;
}
*/
}
