using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BossLevel : MonoBehaviour
{
    [SerializeField] private GameObject thepoint;
    [SerializeField] private Transform[] respawnPoints;
    [SerializeField] private EdgeCollider2D[] Platforms;


    // Start is called before the first frame update
    void Start()
    {
        thepoint = GameObject.Find("RespawnProjectile");
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
