using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ObjPressurePlate: MonoBehaviour
{
public SpriteRenderer spriteRenderer;
public Sprite originalSprite;
public Sprite activatedSprite;
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

void OnTriggerEnter2D(Collider2D other) {
    if (other.CompareTag("PressurePlatable") || other.CompareTag("PlayerIsOnIt")){
       spriteRenderer.sprite = activatedSprite;
    }
}

void OnTriggerExit2D(Collider2D other) {
    if (other.CompareTag("PressurePlatable")|| other.CompareTag("PlayerIsOnIt")) {
         spriteRenderer.sprite = originalSprite;
    }
}
}
