using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class NoShift : MonoBehaviour
{

    private DimShift dimshift;
    // Start is called before the first frame update
    void Start()
    {
        dimshift = GameObject.Find("Frank").GetComponent<DimShift>();
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    void OnTriggerEnter2D(Collider2D col)
    {
        if(col.CompareTag("Player"))
        {
            dimshift.shiftingEnabled = false;
        }
    }

        void OnTriggerExit2D(Collider2D col)
    {
        if(col.CompareTag("Player"))
        {
            dimshift.shiftingEnabled = true;
        }
    }


}
