using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerPressurePlateMod: MonoBehaviour
{

    public SpriteRenderer spriteRenderer;
public Sprite originalSprite;
public Sprite activatedSprite;
public GameObject door;
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

void OnTriggerEnter2D(Collider2D other) {
    //if (other.CompareTag("Player")) {
    //   spriteRenderer.sprite = activatedSprite;
    //}
    spriteRenderer.sprite = activatedSprite;
    door.SetActive(false);
}

/*
void OnTriggerExit2D(Collider2D other) {
    if (other.CompareTag("Player")) {
         spriteRenderer.sprite = originalSprite;
    }
    spriteRenderer.sprite = originalSprite;
}
*/
}
