using UnityEngine;

public class respawnProjectile : MonoBehaviour
{
    private GameObject player;
    private Transform respawnPoint;
    
    void Start()
    {
        player = GameObject.Find("Frank");
        respawnPoint = GameObject.Find("RespawnProjectile").transform;
    }

    void Update()
    {
    }

    private void OnTriggerEnter2D(Collider2D other)
    {
        if (other.gameObject.CompareTag("Player"))
        {
            player.transform.position = respawnPoint.position;
            Debug.Log("Respawn: Move");
        }
    }
}
