using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DynamicRespawn : MonoBehaviour
{
    [SerializeField] private Transform respawn;
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    void OnTriggerEnter2D(Collider2D col)
    {
        if(col.CompareTag("Player"))
        {
            respawn.transform.SetPositionAndRotation(gameObject.transform.position ,Quaternion.identity);
        }    
    }

}
